# Generated by Django 4.0.3 on 2022-05-10 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='annotateur',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=25)),
                ('prenom', models.CharField(max_length=25)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='tweet',
            fields=[
                ('num', models.AutoField(primary_key=True, serialize=False)),
                ('texte', models.TextField()),
                ('nombre_annot', models.IntegerField()),
                ('polarite', models.TextField()),
            ],
        ),
    ]
