# Generated by Django 4.0.3 on 2022-05-26 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_attribut', models.CharField(max_length=15)),
            ],
        ),
        migrations.RenameModel(
            old_name='tweet',
            new_name='tweetForm',
        ),
        migrations.AddField(
            model_name='annotateur',
            name='fonction',
            field=models.CharField(default='étudiant', max_length=30),
            preserve_default=False,
        ),
    ]
