# Generated by Django 4.0.3 on 2022-05-29 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monapp', '0002_attribute_rename_tweet_tweetform_annotateur_fonction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweetform',
            name='nombre_annot',
        ),
        migrations.RemoveField(
            model_name='tweetform',
            name='num',
        ),
        migrations.RemoveField(
            model_name='tweetform',
            name='polarite',
        ),
        migrations.RemoveField(
            model_name='tweetform',
            name='texte',
        ),
        migrations.AddField(
            model_name='tweetform',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
